services:
  service:
    depends_on:
    - db
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    image: nginx:latest
    ports:
    - 8080:80
    volumes:
    - ./html:/usr/share/nginx/html
version: '3'
