services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER={{db_user}}
      - POSTGRES_PASSWORD={{db_password}}
      - POSTGRES_DB={{db_name}}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{db_user}}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  db-network:
    driver: bridge

metadata:
  name: postgres_db
  category: database
  description: "PostgreSQL database with persistent storage and initialization scripts"
  difficulty: beginner
  tags:
    - postgres
    - database
    - sql
  variables:
    - db_user
    - db_password
    - db_name
